# controller_frequency: 5.0
oscillation_timeout: 30.0
oscillation_distance: 0.5
planner_patience: 5.0
controller_patience: 10.0 

TrajectoryPlannerROS:
  max_vel_x: 0.18
  min_vel_x: 0.08
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05 

  acc_lim_theta: 0.6
  acc_lim_x: 2.0
  acc_lim_y: 0.0

  path_distance_bias: 0.8
  goal_distance_bias: 0.6

  holonomic_robot: false
  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.05

DWAPlannerROS:
  max_vel_x: 0.55  
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0


  max_vel_theta: 0.5 
  min_vel_theta: 0 

  acc_lim_x: 2.5 
  acc_lim_theta: 2.5
  acc_lim_y: 0

  yaw_goal_tolerance: 0.25 
  xy_goal_tolerance: 0.15 

  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05 

  path_distance_bias: 64.0