local_costmap:
  width: 3.0
  height: 3.0
  global_frame: map
  resolution: 0.05
  rolling_window: true
  inflation_layer:
    inflation_radius: 0.3
  static_map: false  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}